services:

  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db
    command: npm run start:dev
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:12
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    command: postgres -c 'log_statement=all'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
